/**
 * TypeScript declarations for the Epson ePOS SDK (epos-2.x.x.js).
 *
 * SETUP:
 * 1. Download the Epson ePOS SDK from:
 *    https://download.epson-biz.com/?service=pos  (search "ePOS SDK for JavaScript")
 * 2. Extract and copy the .js file to  src/assets/epos-2.27.0.js
 * 3. The script is loaded via index.html — no npm install needed.
 *
 * The Epson TM-T82X / TM-T88 / TM-T20 series has a built-in HTTP/WebSocket
 * server on port 8008 (HTTP) or 8009 (HTTPS). The ePOS SDK communicates with
 * that server from any browser — no Android app, no USB, no raw TCP needed.
 */

declare namespace epson {
  class ePOSDevice {
    /** Use with createDevice() */
    DEVICE_TYPE_PRINTER: string;

    /**
     * Opens a WebSocket connection to the printer's built-in ePOS server.
     * @param host  Printer IP address (e.g. '192.168.1.100')
     * @param port  ePOS port — always 8008 (HTTP) or 8009 (HTTPS)
     * @param callback  Called with 'OK', 'SSL_CONNECT_OK', or error string
     */
    connect(host: string, port: number, callback: (result: string) => void, options?: object): void;

    /** Closes the WebSocket connection to the printer. */
    disconnect(): void;

    /**
     * Creates a logical device handle (printer, display, etc.) on the connection.
     * @param id       Arbitrary device ID string (use 'local_printer')
     * @param type     Use DEVICE_TYPE_PRINTER
     * @param options  { crypto: false, buffer: false } for direct send mode
     * @param callback Called with (deviceObject, resultCode)
     */
    createDevice(
      id: string,
      type: string,
      options: { crypto: boolean; buffer: boolean },
      callback: (devobj: ePOSPrinter | null, code: string) => void
    ): void;

    /**
     * Releases the device handle gracefully before disconnecting.
     */
    deleteDevice(device: ePOSPrinter, callback: (data: string) => void): void;
  }

  interface ePOSPrinter {
    /**
     * Appends raw ESC/POS bytes to the print buffer.
     * Use this to pass through bytes generated by EscPosService.
     */
    addCommand(data: Uint8Array): void;

    /** Sends the buffered commands to the printer. Fires onreceive when done. */
    send(): void;

    /** Called when the printer responds to a send() call. */
    onreceive: ((res: { success: boolean; code: string; status: number }) => void) | null;

    /** Called when the WebSocket connection drops unexpectedly. */
    ondisconnect: ((data: string) => void) | null;
  }
}
